/** Tnis module has two important objectives which are
 * handle all errors generated by the engine and output a human readable error
 * message for users
 * lpgs the error to a file
 */

import {
	StreamEngineErrorTypes,
	StreamErrorCode,
	StreamEngineError,
	ManagedErrorResult,
	ErrorLevel
} from "@/types/error.types";
import { logger } from "../monitoring/logger";



/** Handles all errors  generated by stream engine*/


const HUMAN_READABLE_MESSAGE: Record<StreamErrorCode, string> = {
	[StreamErrorCode.TIMEOUT]: "The request took too long to fetch standard stream, "
	+ "please try again",
	[StreamErrorCode.PROVIDER_FAILED]: "Failed to fetch streamable links from the several stream providers",
	[StreamErrorCode.CONFIG_READ_ERROR]: "Could not read user stream preferences, "
	+ "default preferences applied",
	[StreamErrorCode.CONFIG_WRITE_ERROR]: "Failed to write user preferences to store "
	+ "check your preferences and try again",
	[StreamErrorCode.NO_STREAM_FOUND]: "No compatible video stream were found for this"
+ " media",
	[StreamErrorCode.UNKNOWN]: "An unexpected error occured while recieving the "
	+ "vidoe stream"
};

const LOG_FILE = "stream-engine.log";

export const errorBase = {
	/** This function create errors specific only to the section tnat called it
	 *
	 */
	createSectionError: (
		devMessage: string,
		code: StreamErrorCode,
		type: StreamEngineErrorTypes,
		rawErr?: unknown,
		level?: ErrorLevel
	): StreamEngineError => {
		const userMessage = HUMAN_READABLE_MESSAGE[code] ||
		HUMAN_READABLE_MESSAGE[StreamErrorCode.UNKNOWN];

		return new StreamEngineError({
			code,
			devMessage,
			userFriendlyMessage: userMessage,
			type,
			originalError: rawErr,
			level
			
		})
	},

	/** Manages error */
	manageError: async (
		err: unknown,
		context: Record<string, any>,
		level?: ErrorLevel
	): Promise<ManagedErrorResult> => {
		let normalizedError: StreamEngineError;

		if (err instanceof StreamEngineError) {
			normalizedError = err;
			if (level)
				normalizedError.level = level;
		} else if (err instanceof Error && err.name === "AbortError") {
			normalizedError  = errorBase.createSectionError(
				"Operation failed due to timeout",
				StreamErrorCode.TIMEOUT,
				"TIMEOUT_TYPE_ERROR",
				err,
				"WARN"
			);
		} else {
			const rawMsg = err instanceof Error ? err?.message : String(err);
			normalizedError  = errorBase.createSectionError(
				`Unhandled Engine Error: ${rawMsg}`,
				StreamErrorCode.UNKNOWN,
				"UNKNOWN_STREAM_TYPE_ERROR",
				err,
				"SEVERE"
			);
		}

		try {
			await logger.errorLogger(
				normalizedError.code,
				normalizedError,
				{...context, type: 	normalizedError.type, devMessage: normalizedError.message},
				LOG_FILE
			);
		} catch(logErr: any) {
				console.error("[ERROR_BASE_LOGGER_FAILURE]: Could not log stream engine error", logErr)
			}

		return {
			code: normalizedError.code,
			usrMessage: normalizedError.userFriendlyMessage,
			engineError: normalizedError
		}
	}
}

